// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGraphicsInfo() {
  return window['go']['services']['GPU']['GetGraphicsInfo']();
}
