// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRamInfo() {
  return window['go']['services']['RAM']['GetRamInfo']();
}
