// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateBatteryReport() {
  return window['go']['services']['System']['GenerateBatteryReport']();
}

export function OpenDeviceManager() {
  return window['go']['services']['System']['OpenDeviceManager']();
}
