// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateBatteryReport():Promise<string>;

export function OpenDeviceManager():Promise<void>;
